### ISSUE TITLE
RTSP

### ISSUE THREAD

**Issue by vladios13** [tropicoo/hikvision-camera-bot#21]
Можно ли как то **получать скриншоты по RTSP потоку**? Удаленно доступ к картинке по RTSP есть, во внешний мир она ходит. 
Пробовал в config.json прописать 
` "host": "rtsp://176.1.1.1:544",`
не вышло, получаю ошибку: `requests.exceptions.InvalidSchema: No connection adapters were found for`
Есть ли какая то альтернатива?

**Comment by tropicoo** [comment]
А если просто `http://176.1.1.1`?

**Comment by vladios13** [comment]
> А если просто `http://176.1.1.1`?

Неа, так не получилось. Я накидал небольшого бота который получает изображения с помощью ffmpeg по RTSP каналу. (Ниже скриншот).
![Безымянный](https://user-images.githubusercontent.com/10531221/78594497-1815fe00-7851-11ea-8dc7-34b3a9fe068a.png)
