### ISSUE TITLE
Error: BadRequest: Chat not found

### ISSUE THREAD

**Issue by alexey7** [tropicoo/hikvision-camera-bot#28]
I get an error:

```
hikvision-camera-bot_1  | 2020-07-12 21:55:16,255 - [DEBUG] - [telegram.vendor.ptb_urllib3.urllib3.connectionpool:410] - https://api.telegram.org:443 POST /bot1...fA/sendMessage HTTP/1.1" 400 73
hikvision-camera-bot_1  | Traceback (most recent call last):
hikvision-camera-bot_1  |   File "bot.py", line 136, in <module>
hikvision-camera-bot_1  |     bot_engine.run()
hikvision-camera-bot_1  |   File "bot.py", line 45, in run
hikvision-camera-bot_1  |     self._send_welcome_message()
hikvision-camera-bot_1  |   File "bot.py", line 70, in _send_welcome_message
hikvision-camera-bot_1  |     self._updater.bot.send_startup_message()
hikvision-camera-bot_1  |   File "/app/hikcamerabot/camerabot.py", line 45, in send_startup_message
hikvision-camera-bot_1  |     self.send_message_all(f'{self.first_name} bot started, see /help for '
hikvision-camera-bot_1  |   File "/app/hikcamerabot/camerabot.py", line 51, in send_message_all
hikvision-camera-bot_1  |     self.send_message(user_id, msg)
hikvision-camera-bot_1  |   File "<decorator-gen-2>", line 2, in send_message
hikvision-camera-bot_1  |   File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 67, in decorator
hikvision-camera-bot_1  |     result = func(*args, **kwargs)
hikvision-camera-bot_1  |   File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 346, in send_message
hikvision-camera-bot_1  |     return self._message(url, data, disable_notification=disable_notification,
hikvision-camera-bot_1  |   File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 175, in _message
hikvision-camera-bot_1  |     result = self._request.post(url, data, timeout=timeout)
hikvision-camera-bot_1  |   File "/usr/local/lib/python3.8/site-packages/telegram/utils/request.py", line 330, in post
hikvision-camera-bot_1  |     result = self._request_wrapper('POST', url,
hikvision-camera-bot_1  |   File "/usr/local/lib/python3.8/site-packages/telegram/utils/request.py", line 244, in _request_wrapper
hikvision-camera-bot_1  |     raise BadRequest(message)
hikvision-camera-bot_1  | telegram.error.BadRequest: Chat not found
```

![image](https://user-images.githubusercontent.com/4357707/87254353-b934d600-c48a-11ea-971b-761ff6168edb.png)

**Comment by tropicoo** [comment]
Are you sure you've created an actualbot as mentioned in Quick Setup?

**Comment by alexey7** [comment]
Sure, I've create a bot using BotFather and inserted a token into "config.json" that looks like `110201543:AAHdqTcvCH1vGWJxfSeofSAs0K5PALDsaw`  but for my bot.

**Comment by tropicoo** [comment]
It seems you haven't started bot in Telegram after creating it in BotFather. Go to your bot and press "START".

**Comment by alexey7** [comment]
What do you mean by starting a bot? 
"/start" command in Telegram?
Bot closes immidiately after start with error code 1.
However, I get the following message in my account: `MY BOT NAME bot started, see /help for available commands`
Of course, all commands do not work after that.

**Comment by tropicoo** [comment]
1. You create a bot in BotFather like "your_botname_bot" and copy API key
2. Then initialize that bot by clicking on it and pressing **start** button directly in Telegram
3. Paste API key to config file and start back-end bot application

**Comment by alexey7** [comment]
Sure. I did exactly the same as you described.

**Comment by tropicoo** [comment]
That's very strange since I've just created new bot in Telegram and successfully started it and got a picture.

![image](https://user-images.githubusercontent.com/888784/87255351-ac1be500-c492-11ea-880f-52188665b362.png)

**Comment by alexey7** [comment]
Back-end app closes with an error that you can see on screenshot in the first message
![image](https://user-images.githubusercontent.com/4357707/87255412-264c6980-c493-11ea-8814-7fa75e8e24fb.png)

**Comment by tropicoo** [comment]
Could you please paste here you full config with masking sensitive data like User ID, Bot API Key, password and camera host.

**Comment by alexey7** [comment]
![image](https://user-images.githubusercontent.com/4357707/87255508-0c5f5680-c494-11ea-93de-796b507d30ad.png)

![image](https://user-images.githubusercontent.com/4357707/87255523-3c0e5e80-c494-11ea-8af8-29038a3d65e7.png)

**Comment by tropicoo** [comment]
I see you have two users in list, could you please remove another one and leave that one who started the Telegram bot.

**Comment by alexey7** [comment]
Sure. I removed the second user and now it works fine. Looks like a bug in JSON parser. An error occurs if there is a space after the comma:
` "allowed_user_ids": [123456, 111222]`
