### ISSUE TITLE
Bot freezes shortly after launch

### ISSUE THREAD

**Issue by alexey7** [tropicoo/hikvision-camera-bot#29]
After executing several commands and sending several pictures, the bot freezes. It stops sending notifications and does not respond to commands.

**Comment by tropicoo** [comment]
Please provide logs records from bot application

**Comment by alexey7** [comment]
It seems that it stops after the first Motion Detection event
After that, the bot does not send a response to commands like `/ getpic_cam_1`
![image](https://user-images.githubusercontent.com/4357707/87256788-4df4ff00-c49e-11ea-8df9-f4b45a314734.png)

**Comment by alexey7** [comment]
![image](https://user-images.githubusercontent.com/4357707/87256977-d58f3d80-c49f-11ea-96d5-c7a2cdc1ad55.png)

**Comment by tropicoo** [comment]
It seems that `ResultEventThread` stopped for a reason. Could you please make `git pull` and restart the container and try again. If this happens once more time check what was the last successful action from your side.

**Comment by alexey7** [comment]
I updated code and now some error with `tmp` directory is logged:
![image](https://user-images.githubusercontent.com/4357707/87257839-2eae9f80-c4a7-11ea-993d-8d6c292e0dfa.png)

**Comment by tropicoo** [comment]
Make `git pull` and restart again. When video recording will be triggered there will be new DEBUG log entry like this:
```
[DEBUG] - [VideoGifManager:58] - Recording video gif for Living Room Camera: ffmpeg -loglevel error -i "rtsp://***:***@***/Streaming/Channels/102/" -t 5 /dev/shm/alert--2020-Jul-13--01-48-05.mp4
```
Copy that ffmpeg command and run in the shell and check if it'd recorded video to the file.

**Comment by alexey7** [comment]
![image](https://user-images.githubusercontent.com/4357707/87258652-e21a9280-c4ad-11ea-84fa-49f55c291e15.png)

I don't know how to run ffmpeg command inside Docker but on pure Windows it works and a file was created

**Comment by tropicoo** [comment]
Maybe if you'll change `ffmpeg` log level from `quiet` to `error` there will be some error message.
If you want check the docker:
1. Run `docker ps`, it'll show your running containers
2. Go to the our bot shell `docker exec -it sources_hikvision-camera-bot_1 sh` and paste your command with ffmpeg error log level and check if there was no any messages and file exists or don't
3. Hit `CTRL+D` to exit

**Comment by alexey7** [comment]
![image](https://user-images.githubusercontent.com/4357707/87259167-fc566f80-c4b1-11ea-971e-813f507a8f80.png)

**Comment by tropicoo** [comment]
That's very strange, interesting which version of ffmpeg is being used in your case. Try to add `-rtsp_transport tcp` after `-loglevel error` to check if this will fix this. Or even set `debug` level, it will show more detailed info (output may contain your camera login/password).

**Comment by alexey7** [comment]
With `-rtsp_transport tcp` ffmpeg works good
![image](https://user-images.githubusercontent.com/4357707/87259532-a6cf9200-c4b4-11ea-8f8f-70b0b4a87a30.png)

**Comment by tropicoo** [comment]
Then for this case currently you can manually add this option to line 92 in `hikcamerabot/constants.py`

**Comment by alexey7** [comment]
Thanks you, now the bot is working fine

**Comment by alexey7** [comment]
> interesting which version of ffmpeg is being used in your case

ffmpeg version 4.3.1

![image](https://user-images.githubusercontent.com/4357707/87289125-e8882900-c504-11ea-9d0d-02663b7d5a15.png)
