### ISSUE TITLE
Got 401 Unauthorized for Hikvision DS-2CD2432F-IW camera

### ISSUE THREAD

**Issue by alexey7** [tropicoo/hikvision-camera-bot#34]
I'm trying to run bot with Hikvision DS-2CD2432F-IW camera and get an error message: 401 Unauthorize

![image](https://user-images.githubusercontent.com/4357707/87476989-030af100-c630-11ea-97b1-c1ea297b6072.png)

In browser next link works good with the same credentials: `http://****:****@192.***.***.***:80/ISAPI/Streaming/channels/102/picture?snapShotImageType=JPEG`

**Comment by tropicoo** [comment]
Was it working before? Check settings on this page
![image](https://user-images.githubusercontent.com/888784/87478174-fdaea600-c631-11ea-9d54-37fe5037ce22.png)

**Comment by alexey7** [comment]
> Was it working before?

No, this is another one camera that has never worked with the bot.

> Check settings on this page

Thanks, I changed the settings for WEB Authentication to digest and that helped.

![image](https://user-images.githubusercontent.com/4357707/87527915-7abf3700-c695-11ea-83c5-f3fd2403aff6.png)
