### ISSUE TITLE
No module named constants

### ISSUE THREAD

**Issue by SA7BNT** [tropicoo/hikvision-camera-bot#4]
After update the bot im running in at some trouble.
Why comes the import error??
Module constants is installed.

![Bildschirmfoto 2019-04-06 um 19 35 46](https://user-images.githubusercontent.com/35367117/55673101-78bbd500-58a3-11e9-97f5-963c590e0064.png)

**Comment by tropicoo** [comment]
Hello,
That's strange, I've just cloned the repo into temporary directory and started it without issues.
Could you please backup your config file and clone the repo into another (new) directory and try to start it from there.

**Comment by SA7BNT** [comment]
Yea very strange. I just make what you wrote. But still getting the same issue. The problem is that i do not have the old version after i make a git pull. :(
Was looking for the feb. version in the commit but cant find it.
Do you have an idea?
![Bildschirmfoto 2019-04-07 um 17 41 49](https://user-images.githubusercontent.com/35367117/55686008-9bf68b00-595c-11e9-9027-31ed924244e6.png)

**Comment by tropicoo** [comment]
Could you please provide the output from command `python -V`.

**Comment by SA7BNT** [comment]
> Could you please provide the output from command `python -V`.

Ahh shit 
`ads-b@debian:~$ python -V`
`Python 2.7.9`
`ads-b@debian:~$`
Will try to install python 3 and let you know

**Comment by SA7BNT** [comment]
![Bildschirmfoto 2019-04-07 um 23 05 04](https://user-images.githubusercontent.com/35367117/55689917-e7c02900-598a-11e9-920d-8cbed2c7ad46.png)

**Comment by tropicoo** [comment]
Looks better :)
This error is caused since no config file was passed as argument to the bot script. 
Please use following command `python bot.py -c config.json` as mentioned in the Usage section. Also, please update your config file since there were added some new variables.

**Comment by SA7BNT** [comment]
Well we are back Online with the bot.
Thanks for help. 
I´m having a nother idea for the (bot) 
Weather TextOverlay. I already tested a bit but now im getting to my end of programming. 
Is that something you should be interested of??

You can also contact me on telegram @sa7bnt
