### ISSUE TITLE
How can I add cameras? 

### ISSUE THREAD

**Issue by goal303** [tropicoo/hikvision-camera-bot#40]
Excuse me, I'm  newbie. I can't add a camera (I have 12 cameras and I want to add them all)

Note that with the default settings, both camera number one and number two display the camera number one.

**Comment by tropicoo** [comment]
Hello, could you please paste here your config with removed or changed cameras user/passwords?

**Comment by goal303** [comment]
thank you for your reply
Not sure if that's what you mean 

{
  "telegram": {
    "token": "0000000000:AAHcssssssspZ6WyUB_rrrrrRyyyyyyguL7rI",
    "allowed_user_ids": [0000000000]
  },
  "watchdog": {
    "enabled": false,
    "directory": ""
  },
  "log_level": "INFO",
  "camera_list": {
    "cam_1": {
      "description": "Kitchen Camera",
      "hashtag": "kitchen",
      "rtsp_port": 554,
      "api": {
        "host": "http://192.168.100.213",
        "auth": {
          "user": "admin",
          "password": "hxxxxxx"
        },
        "stream_timeout": 300
      },
      "alert": {
        "delay": 20,
        "video_gif": {
          "enabled": true,
          "channel": 102,
          "record_time": 5,
          "tmp_storage": "/tmp",
          "loglevel": "quiet",
          "rtsp_transport_type": "tcp"
        },
        "motion_detection": {
          "enabled": false,
          "sendpic": true,
          "fullpic": true
        },
        "line_crossing_detection": {
          "enabled": false,
          "sendpic": true,
          "fullpic": true
        },
        "intrusion_detection": {
          "enabled": false,
          "sendpic": true,
          "fullpic": false
        }
      },
      "livestream": {
        "youtube": {
          "enabled": false,
          "livestream_template": "tpl_kitchen",
          "encoding_template": "x264.kitchen"
        },
        "icecast": {
          "enabled": false,
          "livestream_template": "tpl_kitchen",
          "encoding_template": "vp9.kitchen"
        }
      }
    },
    "cam_2": {
      "description": "Basement Camera",
      "hashtag": "basement",
      "rtsp_port": 554,
      "api": {
        "host": "http://192.168.100.213",
        "auth": {
          "user": "admin",
          "password": "hxxxxxx"
        },
        "stream_timeout": 300
      },
      "alert": {
        "delay": 10,
        "video_gif": {
          "enabled": true,
          "channel": 102,
          "record_time": 5,
          "tmp_storage": "/tmp",
          "loglevel": "quiet",
          "rtsp_transport_type": "tcp"
        },
        "motion_detection": {
          "enabled": false,
          "sendpic": true,
          "fullpic": false
        },
        "line_crossing_detection": {
          "enabled": false,
          "sendpic": true,
          "fullpic": false
        },
        "intrusion_detection": {
          "enabled": false,
          "sendpic": true,
          "fullpic": false
        }
      },
      "livestream": {
        "youtube": {
          "enabled": false,
          "livestream_template": "tpl_basement",
          "encoding_template": "x264.basement"
        },
        "icecast": {
          "enabled": false,
          "livestream_template": "tpl_basement",
          "encoding_template": "vp9.basement"
        }
      }
    }
  }
}

**Comment by tropicoo** [comment]
You have put the same IP address for both cameras: `"host": "http://192.168.100.213/",`, that's why you have data always from the first one.

**Comment by goal303** [comment]
excuse me again
How can I know the IP address for each camera? from the dvr

**Comment by tropicoo** [comment]
I think the IP address of each camera should be listed in DVR's camera list (or somewhere there)

**Comment by goal303** [comment]
thank you for your reply . I will find them
