### ISSUE TITLE
Проблемы с функцией /getvideo_

### ISSUE THREAD

**Issue by SergeoKuznec** [tropicoo/hikvision-camera-bot#42]
Добрый день! 

все работает очень хорошо. но есть проблема при вызове функции /getvideo_cam. Со старыми камерами все ок. с новыми не работает. с этой камерой **DS-2CD2086G2-IU** выдает ошибку :

[ERROR] - [RecordVideoTask:68] - Failed to validate /tmp/cam_2-alert-2022-Mar-19--11-28-14-m>
[ERROR] - [RecordVideoTask:51] - Failed to record /tmp/cam_2-alert-2022-Mar-19--11-28-14-m9l>
[ERROR] - [VideoGifManager:50] - Task RecordVideoTask raised an exception

есть возможность помочь с этим Failed to validate /tmp?

**Comment by tropicoo** [comment]
Доброго дня. Запустіть в контейнері цю команду і покажіть результат помилки:
```bash
ffmpeg -loglevel verbose -i "rtsp://user:password@http://ip_of_your_camera:554/Streaming/Channels/101/" -c:v copy -c:a copy -t 10 /tmp/test_cam_video.mp4
```

**Comment by SergeoKuznec** [comment]
если все правильно сделал, то выдает такое:

ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[tcp @ 0x5565f78fca00] Port missing in uri
rtsp://user:password@http://23.0.0.59:554/Streaming/Channels/101/: Invalid argument

**Comment by vladios13** [comment]
> если все правильно сделал, то выдает такое:
[tcp @ 0x5565f78fca00] Port missing in uri rtsp://user:password@http://23.0.0.59:554/Streaming/Channels/101/: Invalid argument

Порт доступен? Вам не нужно вводить http запрос при вызове RTSP. 

Нужно примерно так: 
`rtsp://user:password@23.0.0.59:554/Streaming/Channels/101/`

На новых камерах возможно доступ быть реализован по другой ссылке (добавлен ISAPI)
`rtsp://user:password@23.0.0.59:554/**ISAPI**/Streaming/Channels/102`

**Comment by SergeoKuznec** [comment]
rtsp://23.0.0.59:554/**ISAPI**/Streaming/Channels/102
через Browser я могу смотреть по такой ссылке видео, смею предположить что порт доступен.

через терминал команда ffmpeg -loglevel verbose -i "rtsp://user:password@23.0.0.59:554/**ISAPI**/Streaming/Channels/102" -c:v copy -c:a copy -t 10 /tmp/test_cam_video.mp4 по прежнему выдает ту же самую ошибку [tcp @ 0x5653798b4a40] **Port missing in uri**

но если запустить команду без авторизации, ffmpeg -loglevel verbose -i "**rtsp://23.0.0.59:554**/**ISAPI**/Streaming/Channels/102" -c:v copy -c:a copy -t 10 /tmp/test_cam_video.mp4, то выдает такое (в данном случае с портом все ок, проблема с Unauthorized): 
**[tcp @ 0x55e6aef60a00] Starting connection attempt to 23.0.0.59 port 554
[tcp @ 0x55e6aef60a00] Successfully connected to 23.0.0.59 port 554**
[rtsp @ 0x55e6aef5e700] method DESCRIBE failed: 401 **Unauthorized**
rtsp://23.0.0.59:554/**ISAPI**/Streaming/Channels/102: Server returned 401 Unauthorized (authorization failed)

**Comment by tropicoo** [comment]
Можливо є специфічні символи в паролі, котрі впливають на парсинг повної URL.

**Comment by SergeoKuznec** [comment]
да, действительно, при смене пароля команда стала выполняться

[tcp @ 0x5556597aba40] Starting connection attempt to 23.0.0.59 port 554
[tcp @ 0x5556597aba40] Successfully connected to 23.0.0.59 port 554
[rtsp @ 0x5556597a9700] SDP:
v=0
o=- 1647971951808077 1647971951808077 IN IP4 23.0.0.59
s=Media Presentation
e=NONE
b=AS:5050
t=0 0
a=control:rtsp://23.0.0.59:554/**ISAPI**/Streaming/Channels/102/
m=video 0 RTP/AVP 26
c=IN IP4 0.0.0.0
b=AS:5000
a=recvonly
a=x-dimensions:640,360
a=control:rtsp://23.0.0.59:554/**ISAPI**/Streaming/Channels/102/trackID=1
a=rtpmap:26 JPEG/90000
a=Media_header:MEDIAINFO=494D4B48010200000400040000000000000000000000000000000000000000000000000000000000;
a=appversion:1.0

[rtsp @ 0x5556597a9700] setting jitter buffer size to 500
[rtsp @ 0x5556597a9700] max delay reached. need to consume packet
**[rtsp @ 0x5556597a9700] RTP: missed 2 packets
[rtsp @ 0x5556597a9700] Missing packets; dropping frame.**

видео файл в итоге появился в папке /tmp

но в телеграмме, пока еще выдает туже самую ошибку
Failed to record /tmp/cam_5-2022-Mar-22--17-54-12-rtur.mp4.
Event type: record_videogif
Check logs.


из лог файла
Mar 22 10:25:02 ubnt 9cc0a6f379c4[1568]: AttributeError: 'NoneType' object has no attribute 'chat'
Mar 22 10:25:04 ubnt 9cc0a6f379c4[1568]: 2022-03-22 10:25:04,848 - [ERROR] - [RecordVideoTask:68] - Failed to validate /tmp/cam_1-alert-2022-Mar-22--10-25-04-c>
Mar 22 10:25:04 ubnt 9cc0a6f379c4[1568]: 2022-03-22 10:25:04,848 - [ERROR] - [RecordVideoTask:51] - Failed to record /tmp/cam_1-alert-2022-Mar-22--10-25-04-clb>
Mar 22 10:25:04 ubnt 9cc0a6f379c4[1568]: 2022-03-22 10:25:04,849 - [ERROR] - [VideoGifManager:50] - Task RecordVideoTask raised an exception
Mar 22 10:25:04 ubnt 9cc0a6f379c4[1568]: Traceback (most recent call last):
Mar 22 10:25:04 ubnt 9cc0a6f379c4[1568]:   File "/app/hikcamerabot/utils/task.py", line 46, in _handle_task_result
Mar 22 10:25:04 ubnt 9cc0a6f379c4[1568]:     task.result()
Mar 22 10:25:04 ubnt 9cc0a6f379c4[1568]:   File "/app/hikcamerabot/services/tasks/video.py", line 40, in run
Mar 22 10:25:04 ubnt 9cc0a6f379c4[1568]:     if await self._record():
Mar 22 10:25:04 ubnt 9cc0a6f379c4[1568]:   File "/app/hikcamerabot/services/tasks/video.py", line 53, in _record
Mar 22 10:25:04 ubnt 9cc0a6f379c4[1568]:     self._context.chat.id

**Comment by tropicoo** [comment]
Я маю підозру, що ця помилка швидше за все була виправлена в новому релізі.

**Comment by SergeoKuznec** [comment]
Да, все ок. Работает! Основная проблема была с паролем. Как скачал званого, изменил пароль без символов, все заработало. Спасибо!
