### ISSUE TITLE
[BUG] Commands Messages Fail Due To Too Many Cameras

### ISSUE THREAD

**Issue by thepeanutgalleryandco** [tropicoo/hikvision-camera-bot#44]
Hi @tropicoo 

First off, well done on a great repo!

I am trying to help a friend where they want to be able to send photos and videos to a group instead of an indivisual user, and from there, they would like to be able to add quite a large number of cameras as they want to be able to use it for the likes of a neighbourhood watch for example.

The problem comes in when you add too mamy cameras, I think from around 10 or 12 cameras, the message becomes too long that the bot is trying to send (O think the telegram message is 10000 characters) when listing the commamds, and the bot becomes unuseable as it keeps erroring.

I think you will need to abstract a few things with the messages that will maybe only list camera names or perhaps customer names and when clicking on a customer, show their cameras only and then a list of commands. This will make the list shorter, but would still have an issue id that customer has a list of 10 or 12 cameras.

I think you will also need to check if there is still space in the message to be sent for the camera and its commands and if not, then send the current message text and start a new message and loop through that until allessages have been sent.

Cheers, and thanks for the great work!

**Comment by tropicoo** [comment]
Hello, thanks for raising your issues and feature request.
Is this something you would like with grouping your cameras?

![image](https://user-images.githubusercontent.com/888784/166001790-18dbec6e-a5e9-4352-af40-449d7c84ce3b.png)

**Comment by thepeanutgalleryandco** [comment]
@tropicoo Group is a good idea and a good start. I think there will still be an issue of someone has more than 10 or 12 cameras with bigger names as it makes all the command names bigger as well. Some form of "paging" or multiple message logic is needed to cater for this scenario as well. I do like groups as well, so both are needed :)

**Comment by tropicoo** [comment]
> bigger names as it makes all the command names bigger

Do you mean camera descriptions?
