### ISSUE TITLE
Getting Error when using h265 video codec in Hikvision camera

### ISSUE THREAD

**Issue by xozy22** [tropicoo/hikvision-camera-bot#47]
I am getting an error when I am using H265 codec in Hikvision camera.
Is there a fix how to use H265 instead H264 or would that have to be implemented?

Anyway thank you for your great work. The bot works very well!
Iam struggling a little bit with rewind and record time but over all it's amazing.

**Comment by tropicoo** [comment]
If you turn off SRS re-stream in the camera config, it should work. FLV stream (cam video -> srs -> telegram) doesn't support HEVC (H.265)

```json
        "srs": {
          "enabled": false,
```

**Comment by tropicoo** [comment]
Please reopen in case of any questions
