### ISSUE TITLE
Possible to use it with Foscam

### ISSUE THREAD

**Issue by SA7BNT** [tropicoo/hikvision-camera-bot#5]
Hallo,

is it possible that i can use it with a Foscam IPcam??
Or maybe is it possible that you can add the Foscam IPcam to the bot??
Here are some commands.
https://www.github.developerdan.com/foscam-client/index.html
https://www.foscam.es/descarga/Foscam-IPCamera-CGI-User-Guide-AllPlatforms-2015.11.06.pdf
Should be a great feature.

Best

**Comment by tropicoo** [comment]
Hello,
Unfortunately I don't own any Foscam camera to try implementing its features. Even with HikVision camera I needed to test different scenarios to see how it behaves.
Best Regards
