### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by RealLord** [tropicoo/hikvision-camera-bot#59]
hikvision_srs_server    | [2022-10-24 17:15:51.372][Trace][1][y88180x3] RTC: connection manager run, conns=0
hikvision_camera_bot    | Config validation error - "config.json": {'camera_list': {'picture': ['Missing data for required field.'], 'alert': {'intrusion_detection': {'send_text': ['Missing data for required field.']}, 'motion_detection': {'send_text': ['Missing data for required field.']}, 'line_crossing_detection': {'send_text': ['Missing data for required field.']}}}}
hikvision_camera_bot    | Fix config files and try again.
hikvision_srs_server    | [2022-10-24 17:15:56.362][Trace][1][15305cb6] Hybrid cpu=0.00%,14MB
hikvision_camera_bot exited with code 1
hikvision_camera_bot    | Config validation error - "config.json": {'camera_list': {'picture': ['Missing data for required field.'], 'alert': {'intrusion_detection': {'send_text': ['Missing data for required field.']}, 'motion_detection': {'send_text': ['Missing data for required field.']}, 'line_crossing_detection': {'send_text': ['Missing data for required field.']}}}}
hikvision_camera_bot    | Fix config files and try again.
hikvision_camera_bot    | Config validation error - "config.json": {'camera_list': {'picture': ['Missing data for required field.'], 'alert': {'intrusion_detection': {'send_text': ['Missing data for required field.']}, 'motion_detection': {'send_text': ['Missing data for required field.']}, 'line_crossing_detection': {'send_text': ['Missing data for required field.']}}}}
hikvision_camera_bot    | Fix config files and try again.
hikvision_camera_bot    | Config validation error - "config.json": {'camera_list': {'picture': ['Missing data for required field.'], 'alert': {'motion_detection': {'send_text': ['Missing data for required field.']}, 'line_crossing_detection': {'send_text': ['Missing data for required field.']}, 'intrusion_detection': {'send_text': ['Missing data for required field.']}}}}
hikvision_camera_bot    | Fix config files and try again.

All section that was in 1.6 & 1.7 release as new features doesn't working. Config errors.

**Comment by tropicoo** [comment]
Hey, I've forgotten to add new fields to the second camera in the `config-template.json` file. I've just pushed the update.
Please reconfigure from the updated template.

**Comment by tropicoo** [comment]
Please reopen if the issue still presists
