### ISSUE TITLE
Is it possible to have Line Crossing, instead of Motion Detection as trigger for sending photo?

### ISSUE THREAD

**Issue by Klagio** [tropicoo/hikvision-camera-bot#7]
Is it possible to have Line Crossing, instead of Motion Detection as trigger for sending photo?

**Comment by Klagio** [comment]
I disable motion detection because of too many false positive.

So I enevbled Line Crossing, it works with Hikvision app sending me email, but I rather have pictures in Telegram and not in email.

Is this possible?

**Comment by tropicoo** [comment]
Hello,
I will investigate to see what can I do. Could you please provide the full name of your HikVision camera model.
Best Regards

**Comment by Klagio** [comment]
DS-2CD2T22WD-I5
DS-2CD2342WD-I
DS-2CD2142FWD-I
DS-2CD2120F-I

From my understanding they all work the same. Let me know if I can help from my side

**Comment by Klagio** [comment]
These are the events

SUPPORTED TYPES
Supported sensor/event types are:

Motion
Line Crossing
Field Detection
Video Loss
Tamper Detection
Shelter Alarm
Disk Full
Disk Error
Net Interface Broken
IP Conflict
Illegal Access
Video Mismatch
Bad Video
PIR Alarm
Face Detection
Scene Change Detection

**Comment by Klagio** [comment]
Maybe this file helps?

http://oversea-download.hikvision.com/uploadfile/Leaflet/ISAPI/HIKVISION%20ISAPI_2.0-IPMD%20Service.pdf

**Comment by Klagio** [comment]
Have a look at this service etlgr.com

**Comment by tropicoo** [comment]
Hello,
Please try the Line Crossing Detection and leave feedback. This feature caused some changes in the config file structure - basically speaking `motion_detection` section moved under `alert` with `line_crossing_detection`. Please update as described in Configuration section of README.
New commands are:
```
/lndetection_on_cam_*
/lndetection_off_cam_*
```

**Comment by tropicoo** [comment]
I'm closing this for now since it seems Line Crossing Detection works. Re-open if needed.
Thanks.
