### ISSUE TITLE
Snapshot API issue

### ISSUE THREAD

**Issue by SA7BNT** [tropicoo/hikvision-camera-bot#8]
Hej,
i just maked a git pull and was running in at this issue.
![Bildschirmfoto 2019-06-19 um 22 10 03](https://user-images.githubusercontent.com/35367117/59797368-cd39f280-92df-11e9-8f00-8f4082667c2a.JPEG)
Also in the log output there is a fail.

**Comment by tropicoo** [comment]
Hi,
Please make `git pull` one more time and check if the issue is still present. Also, check the configuration structure if it's up-to-date as decribed in README.
Thanks

**Comment by SA7BNT** [comment]
I maked a git pull but was still problem.
I looked at the config one more time and there seems the issue was
Please look at your config.template.json
https://github.com/tropicoo/hikvision-camera-bot/blob/d488145e3d5373b7c9babb702550c48963768c90/config-template.json#L21-L22
It seems that ISAPI is missing
Just one little issue in the log (see Pic) If i stop YT it wrote that he starts YT
![Bildschirmfoto 2019-06-20 um 21 40 30](https://user-images.githubusercontent.com/35367117/59876564-3f740b00-93a4-11e9-8f09-b1881a8f47ff.JPEG)

**Comment by tropicoo** [comment]
Ah, I see. Updated template and README and fixed log message typo.
Could you please try
```
"motion_detection": "ISAPI/System/Video/inputs/channels/1/motionDetection",
```
instead of
```
"motion_detection": "/MotionDetection/1/", 
```
and check if it works for you.
Thanks.

**Comment by SA7BNT** [comment]
Ok Enable/Disable Line/Motion Detection is working. 
The markers were checkt/decheckt
But if it is enabled and i work through it i do not get a pic to telegram from the cam.

**Comment by tropicoo** [comment]
That strange. Could please write more in details how you tested it. 
To get it to work you must simply enable either Motion Detection (MD) and/or Line Crossing Detection (LD) and enable Alert (Alarm). 
One thing I'm experiencing with LD is that I need to try harder to cross the line and trigger the Alert Stream which is monitored by camera bot.

**Comment by SA7BNT** [comment]
OK, if i first enable LD and then Alarm i got an issue (see pic)
If i first run alarm and then LD or MD all is fine but no pic comes to Telegram.
![Bildschirmfoto 2019-06-20 um 22 22 05](https://user-images.githubusercontent.com/35367117/59879287-9d0b5600-93aa-11e9-810d-80bf966e5fe5.JPEG)
![Bildschirmfoto 2019-06-20 um 22 24 35](https://user-images.githubusercontent.com/35367117/59879304-a98fae80-93aa-11e9-8a6d-3c9f803d5900.JPEG)

**Comment by tropicoo** [comment]
It seems you forgot to include `http://` protocol to your camera host (IPv4).
Example `http://192.168.0.1`. I've updated both template and README.

**Comment by SA7BNT** [comment]
No!?
![Bildschirmfoto 2019-06-20 um 22 38 05](https://user-images.githubusercontent.com/35367117/59879937-253e2b00-93ac-11e9-8394-65738a63ade1.JPEG)

**Comment by tropicoo** [comment]
My bad, sorry. I think I've found the root of the problem.
I've changed the logic with concatenating URL host and path. I hope it will now work :)
Make `git pull` once more.

**Comment by SA7BNT** [comment]
Still same problem. If i first enable alarm and then LD i got the issue. 
![Bildschirmfoto 2019-06-20 um 22 51 08](https://user-images.githubusercontent.com/35367117/59880752-1eb0b300-93ae-11e9-8022-e4dd19152a1d.JPEG)
And now if i first take LD and then alarm comes this.
![Bildschirmfoto 2019-06-20 um 22 55 21](https://user-images.githubusercontent.com/35367117/59880912-85ce6780-93ae-11e9-9c9d-ef4aa3f27686.JPEG)
Take your time. It seems to be a little bit tricky.
Will test more tomorrow.

**Comment by tropicoo** [comment]
That `urllib3.connectionpool - WARNING` can be absolutely ignored. I will implement logging filter to suppress it.

**Comment by SA7BNT** [comment]
God morning @tropicoo 
I just maked a git pull and it seems that we are back online. LD is working now, and i also got a pic. to Telegram. Great work. 
Maybe i am wrong but in the config.template.json is still the "endpoint" picture without ISAPI
https://github.com/tropicoo/hikvision-camera-bot/blob/cd244f7968ae1fe0bc9eacb3855ed16fea891ad5/config-template.json#L21
Thanks for your great work.
