### ISSUE TITLE
Add YT templates 

### ISSUE THREAD

**Issue by SA7BNT** [tropicoo/hikvision-camera-bot#9]
Could it be an idee to add YT templates for uploading the stream in different resolutions (FFMPEG reencode)?
In my summer residence i cant upload 2mb/s 
So why not make 4 different templates low/mid/high/ultrahigh 320/640/1280/1920 and for the bitrate let the user make the choice inside these templates.
What are you thinking about that?

**Comment by tropicoo** [comment]
Yup, good idea. Will implement this.

**Comment by tropicoo** [comment]
Done, please `git pull`, check README with updated configuration for Livestream Templates and let's find some bugs.

**Comment by SA7BNT** [comment]
Ok, will start with that
![Bildschirmfoto 2019-06-26 um 22 51 13](https://user-images.githubusercontent.com/35367117/60214051-097fcc80-9865-11e9-98b8-c0c1c1aa34bb.JPEG)

**Comment by tropicoo** [comment]
Good catch. could you please start it without passing argument `-c config.json`,
just `python bot.py`.

**Comment by SA7BNT** [comment]
Shure, done 

![Bildschirmfoto 2019-06-26 um 23 00 17](https://user-images.githubusercontent.com/35367117/60214665-34b6eb80-9866-11e9-92bc-b0d8fb68f907.JPEG)

**Comment by tropicoo** [comment]
Ah, I've got it. You have Python 3.4. Do you have any ability to update it to 3.7 (or at least 3.6)?

**Comment by SA7BNT** [comment]
Yes running Python 3.4.2 
Will give it a try tomorrow. The ThinClient comes out with the white flag *lol* was not the strongest machine.
Will try on another machine and let you know. 
BTW: Great fast work. RESPECT!!

**Comment by SA7BNT** [comment]
Hmmmmm, 
sudo pip3 install python-telegram
sudo pip3 install python-telegram-bot
But still getting no module error.
Something i miss?
![Bildschirmfoto 2019-06-27 um 11 17 01](https://user-images.githubusercontent.com/35367117/60253989-6020f100-98cd-11e9-880e-7054036f7b68.JPEG)

**Comment by tropicoo** [comment]
That's strange. Try this
```bash
# Can show another location
$ which pip3
/usr/local/bin/pip3

# To to Python executable which is used by pip3
$ head -n1 /usr/local/bin/pip3
#!/usr/local/bin/python3

# Check if Python 3 path from previous step is the same
$ which python3
/usr/local/bin/python3
```

**Comment by SA7BNT** [comment]
Ok it seems that i got python3.7 at work now. 
Here comes the new issue.
![Bildschirmfoto 2019-06-27 um 18 43 18](https://user-images.githubusercontent.com/35367117/60284324-8feee980-990b-11e9-9a17-d6164507e9f6.JPEG)

**Comment by tropicoo** [comment]
Please check if you don’t have single quotes inside the `config.json` file, or maybe there is a word without any quotes which needs to be in double quotes.

**Comment by SA7BNT** [comment]
Done!
![Bildschirmfoto 2019-06-27 um 19 42 31](https://user-images.githubusercontent.com/35367117/60288103-c597d080-9913-11e9-9c67-9314cd08c544.JPEG)

**Comment by tropicoo** [comment]
Again my bad, forgot to change in `config-template.json` and README `live_stream` key to `livestream`. P

**Comment by SA7BNT** [comment]
Ok now we are Online again.
![Bildschirmfoto 2019-06-27 um 22 04 17](https://user-images.githubusercontent.com/35367117/60296999-98551d80-9927-11e9-8c62-94b65c222328.JPEG)
Will test Youtube and let you know how it works. If i got some more issues i will let you know.
Best Tim

**Comment by SA7BNT** [comment]
Have you ffmpeg log output enabled?? 
Where do i find it?

**Comment by tropicoo** [comment]
OK, added it too. Make `git pull` and add `"loglevel": "info"` to your livestream templates. All level flags are listed here https://ffmpeg.org/ffmpeg.html, just CMD+F `-loglevel`.

**Comment by SA7BNT** [comment]
Arguments, may be will see. 
If i say Icecast2 how are you thinking about that? ;)

**Comment by tropicoo** [comment]
Need mode details how it should work :)

**Comment by tropicoo** [comment]
Just reminded myself that I was using icecast 11 years ago for streaming local radio.
If I didn't miss the point, you want to stream same video stream to icecast2 server.
Will look at it.

**Comment by tropicoo** [comment]
Got it working. I will open a new issue for icecast support.
