### ISSUE TITLE
I have a question about the configuration of the alert and how it would work, and how to test it?

### ISSUE THREAD

**Issue by Gui-henrique-dos-santos** [tropicoo/hikvision-camera-bot#93]
{
  "telegram": {
    "api_id": xxxxxxxxx,
    "api_hash": "xxxxxxxxxxxxxxxxxxxxxx",
    "lang_code": "en",
    "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "chat_users": [
      xxxxxxxxxxxxxxxx,
      xxxxxxxxxxxxxx
    ],
    "alert_users": [
      xxxxxxxxxxx,
      xxxxxxxxxxx
    ],
    "startup_message_users": [
      xxxxxxxxxxxxxxx,
      xxxxxxxxxxxxxxxx
    ]
  },
  "log_level": "DEBUG",
  "camera_list": {
    "cam_1": {
      "hidden": false,
      "description": "Kitchen",
      "hashtag": "kitchen",
      "group": "Default group",
      "api": {
        "host": "http://172.25.x.xxxxx",
        "port": 80,
        "auth": {
          "user": "xxxxxxxxxxx",
          "password": "xxxxxxxxxxxxxxxxxxxx",
          "type": "digest_cached"
        },
        "stream_timeout": 10
      },
      "rtsp_port": 554,
      "picture": {
        "on_demand": {
          "channel": 101
        },
        "on_alert": {
          "channel": 101
        }
      },
      "video_gif": {
        "on_demand": {
          "channel": 101,
          "record_time": 10,
          "rewind_time": 10,
          "tmp_storage": "/tmp",
          "loglevel": "error",
          "rtsp_transport_type": "tcp"
        },
        "on_alert": {
          "channel": 101,
          "record_time": 10,
          "rewind_time": 10,
          "rewind": true,
          "tmp_storage": "/tmp",
          "loglevel": "error",
          "rtsp_transport_type": "tcp"
        }
      },
      "alert": {
        "delay": 5,
        "motion_detection": {
          "enabled": true,
          "sendpic": true,
          "fullpic": true,
          "send_videogif": true,
          "send_text": true
        },
        "line_crossing_detection": {
          "enabled": true,
          "sendpic": true,
          "fullpic": true,
          "send_videogif": true,
          "send_text": true
        },
        "intrusion_detection": {
          "enabled": true,
          "sendpic": true,
          "fullpic": true,
          "send_videogif": true,
          "send_text": true
        }
      },
      "livestream": {
        "youtube": {
          "enabled": false,
          "livestream_template": "tpl_kitchen",
          "encoding_template": "direct.kitchen_youtube"
        },
        "telegram": {
          "enabled": false,
          "livestream_template": "tpl_kitchen",
          "encoding_template": "direct.kitchen_telegram"
        },
        "srs": {
          "enabled": false,
          "livestream_template": "tpl_kitchen",
          "encoding_template": "direct.kitchen_srs"
        },
        "dvr": {
          "enabled": false,
          "local_storage_path": "/data/dvr",
          "livestream_template": "tpl_kitchen",
          "encoding_template": "direct.kitchen_dvr",
          "upload": {
            "delete_after_upload": true,
            "storage": {
              "telegram": {
                "enabled": false,
                "group_id": -10000000
              }
            }
          }
        },
        "icecast": {
          "enabled": false,
          "livestream_template": "tpl_kitchen",
          "encoding_template": "vp9.kitchen"
        }
      },
      "command_sections_visibility": {
        "general": true,
        "infrared": true,
        "motion_detection": true,
        "line_detection": true,
        "intrusion_detection": true,
        "alert_service": true,
        "stream_youtube": true,
        "stream_telegram": true,
        "stream_icecast": true
      }
    },
    "cam_2": {
      "hidden": false,
      "description": "Basement",
      "hashtag": "basement",
      "group": "Default group",
      "api": {
        "host": "http://192.168.1.2",
        "port": 80,
        "auth": {
          "user": "dummy-user",
          "password": "dummy-password",
          "type": "digest_cached"
        },
        "stream_timeout": 10
      },
      "rtsp_port": 554,
      "picture": {
        "on_demand": {
          "channel": 101
        },
        "on_alert": {
          "channel": 101
        }
      },
      "video_gif": {
        "on_demand": {
          "channel": 101,
          "record_time": 10,
          "rewind_time": 10,
          "tmp_storage": "/tmp",
          "loglevel": "error",
          "rtsp_transport_type": "tcp"
        },
        "on_alert": {
          "channel": 101,
          "record_time": 10,
          "rewind_time": 10,
          "rewind": false,
          "tmp_storage": "/tmp",
          "loglevel": "error",
          "rtsp_transport_type": "tcp"
        }
      },
      "alert": {
        "delay": 15,
        "motion_detection": {
          "enabled": false,
          "sendpic": true,
          "fullpic": false,
          "send_videogif": true,
          "send_text": true
        },
        "line_crossing_detection": {
          "enabled": false,
          "sendpic": true,
          "fullpic": false,
          "send_videogif": true,
          "send_text": true
        },
        "intrusion_detection": {
          "enabled": false,
          "sendpic": true,
          "fullpic": false,
          "send_videogif": true,
          "send_text": true
        }
      },
      "livestream": {
        "youtube": {
          "enabled": false,
          "livestream_template": "tpl_basement",
          "encoding_template": "direct.basement_youtube"
        },
        "telegram": {
          "enabled": false,
          "livestream_template": "tpl_basement",
          "encoding_template": "direct.basement_telegram"
        },
        "srs": {
          "enabled": false,
          "livestream_template": "tpl_basement",
          "encoding_template": "direct.basement_srs"
        },
        "dvr": {
          "enabled": false,
          "local_storage_path": "/data/dvr",
          "livestream_template": "tpl_basement",
          "encoding_template": "direct.basement_dvr",
          "upload": {
            "delete_after_upload": true,
            "storage": {
              "telegram": {
                "enabled": false,
                "group_id": -10000000
              }
            }
          }
        },
        "icecast": {
          "enabled": false,
          "livestream_template": "tpl_basement",
          "encoding_template": "vp9.basement"
        }
      },
      "command_sections_visibility": {
        "general": true,
        "infrared": true,
        "motion_detection": true,
        "line_detection": true,
        "intrusion_detection": true,
        "alert_service": true,
        "stream_youtube": true,
        "stream_telegram": true,
        "stream_icecast": true
      }
    }
  }
}

**Comment by tropicoo** [comment]
If in the logs you don't see any errors and you can turn on/off mention detection through the Telegram Bot command, you should be able to get alerts when the Hikvision camera triggers an alert event.

You can go to the Web-UI of your camera and check whether commands from the bot enable/disable the functionality. For Line Crossing Detection you need to create on the Web-UI trigger-lines/rectangles (there are probably more proper words but anyway).
